  name: CD

  on:
    push:
      branches: [main]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Install dependency
          run: npm Install

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy in EC2
      env:
        PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
        HOSTNAME: ${{ secrets.HOSTNAME  }}
        USERNAME: $${{  secrets.USERNAME  }}

      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StricHostKeyChecking=no -i pirvate_key ${USERNAME}@${HOSTNAME} '
        cd ./aws_rkddml &&
        git reset --hard &&
        git pull &&
        npm install &&
        pm2 stop index.js &&
        pm2 start index.js'